Repository SWYP-index/swyp-frontend, pull requests merged in 2025-07, with the labels that each got.

#2 🎨 Style : tailwind 색상 커스텀 추가
  tailwind.config.js
Labels: 💄 Design

#6 💄✨ [Design, Feat] : 메인페이지 전체적인 마크업 및 기능
  public/icons/arrowDown.svg
  public/icons/arrowRight.svg
  public/icons/arrowUp.svg
  public/icons/bar.svg
  public/icons/imgExam.svg
  public/icons/notification.svg
  public/icons/polygon.svg
  public/icons/profile.svg
  public/icons/search.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/app/write/page.tsx
  src/components/header/emojiDropDown.tsx
  src/components/header/filterDropDown.tsx
  src/components/header/header.tsx
  src/components/header/notificationDropDown.tsx
  src/components/header/profileDropDwon.tsx
  src/components/header/searchBar.tsx
  src/components/mainPage/bookReport.tsx
  src/components/mainPage/bookShelfSection.tsx
  src/components/mainPage/deskSection.tsx
  src/components/mainPage/entryAuthModal.tsx
  src/components/mainPage/fixedFooter.tsx
  src/components/mainPage/heroSection.tsx
  src/components/mainPage/mainPage.tsx
Labels: ✨ Feat, 💄 Design

#18 [Design] 독서 리포트 페이지 마크업 구현
  package-lock.json
  package.json
  public/icons/RectangleFinish.svg
  public/icons/RectangleStart.svg
  public/icons/RectangleWrite.svg
  public/icons/emotionIcon.svg
  public/icons/noReadIcon.svg
  public/icons/todayDot.svg
  src/app/globals.css
  src/app/report/page.tsx
  src/components/mainPage/bookReport.tsx
  src/components/reportPage/calendar.css
  src/components/reportPage/calendar.tsx
  src/components/reportPage/myBookHistory.css
  src/components/reportPage/myBookHistory.tsx
  tailwind.config.js
Labels: 💄 Design

#19 [Design] 기록하기 페이지 마크업 완료
  public/icons/closeIcon.svg
  public/icons/emotion/negativeIcon.svg
  public/icons/emotion/neutralityIcon.svg
  public/icons/emotion/positiveIcon.svg
  public/icons/emotion/thoughtIcon.svg
  public/icons/plusIcon.svg
  src/app/globals.css
  src/app/write/page.tsx
  src/components/header/emojiDropDown.tsx
  src/components/header/filterDropDown.tsx
  src/components/header/header.tsx
  src/components/header/searchBar.tsx
  src/components/mainPage/bookReport.tsx
  src/components/mainPage/bookShelfSection.tsx
  src/components/mainPage/deskSection.tsx
  src/components/mainPage/entryAuthModal.tsx
  src/components/reportPage/myBookHistory.tsx
  src/components/writePage/bookModal.tsx
  src/components/writePage/indexRecord.tsx
  tailwind.config.js
Labels: 💄 Design

#21 [Feat]코드제거 및 페이지 제거
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/app/test/page.tsx
  src/components/modal/login/page.tsx
  src/hooks/.gitkeep
  src/hooks/login/useLogin.ts
Labels: 🐛 bug, 🔧 Fix
