Repository SWYP-index/swyp-frontend, pull requests merged in 2025-08, with the labels that each got.

#25 [Feat] 기록하기 페이지 기능 구현 완료
  package-lock.json
  package.json
  public/icons/closeIcon2.svg
  public/icons/emotion/anger.png
  public/icons/emotion/awkward.png
  public/icons/emotion/confusion.png
  public/icons/emotion/consolation.png
  public/icons/emotion/displeased.png
  public/icons/emotion/doubt.png
  public/icons/emotion/embarrassed.png
  public/icons/emotion/excitement.png
  public/icons/emotion/fear.png
  public/icons/emotion/insight.png
  public/icons/emotion/inspiration.png
  public/icons/emotion/moved.png
  public/icons/emotion/negativeIcon.svg
  public/icons/emotion/neutralityIcon.svg
  public/icons/emotion/pleasant.png
  public/icons/emotion/positiveIcon.svg
  public/icons/emotion/realize.png
  public/icons/emotion/sad.png
  public/icons/emotion/selfExamination.png
  public/icons/emotion/sorry.png
  public/icons/emotion/stuffy.png
  public/icons/emotion/surprise.png
  public/icons/emotion/sympathy.png
  public/icons/emotion/thoughtIcon.svg
  public/icons/plusIconDisabled.svg
  src/apis/book/bookApi.ts
  src/app/write/page.tsx
  src/components/header/emojiDropDown.tsx
  src/components/header/filterDropDown.tsx
  src/components/writePage/bookModal.tsx
  src/components/writePage/indexRecord.tsx
  src/components/writePage/routingPopUp.tsx
  src/constants/emotion.ts
  src/hooks/login/useLogin.ts
  src/hooks/main/useGetDeskData.ts
  src/hooks/write/usePostRecordData.ts
  src/lib/axios.ts
  src/types/index.ts
Labels: ✨ Feat

#27 [Fix] 토큰 재발급 코드 수정
  src/lib/axios.ts
Labels: 🔧 Fix

#30 [Design,Feat] 검색결과 페이지 마크업 및 기능 구현완료
  next.config.ts
  public/icons/noEmotionData.svg
  src/apis/book/bookApi.ts
  src/app/result/page.tsx
  src/components/header/header.tsx
  src/components/header/searchBar.tsx
  src/hooks/search/useInfinite.ts
  src/hooks/search/useSearch.ts
  src/lib/axios.ts
Labels: ✨ Feat, 🔧 Fix, 💄 Design

#31 [Fix] 검색결과페이지 서버 컴포넌트와 클라이언트 컴포넌트 분리
  src/app/detail/page.tsx
  src/app/result/page.tsx
  src/components/search/resultSearchPage.tsx
Labels: 🔧 Fix

#33 [Feat] 독서 리포트 api 연동 마무리
  src/apis/book/bookApi.ts
  src/app/write/page.tsx
  src/components/mainPage/bookReport.tsx
  src/components/mainPage/bookShelfSection.tsx
  src/components/mainPage/deskSection.tsx
  src/components/mainPage/heroSection.tsx
  src/components/reportPage/calendar.tsx
  src/components/reportPage/myBookHistory.tsx
  src/components/writePage/routingPopUp.tsx
  src/hooks/report/useGetRecordedData.ts
  src/types/index.ts
Labels: ✨ Feat

#40 [Design] 헤더 스크롤해도 고정 되도록 수정
  public/icons/heroHeader.svg
  src/app/report/page.tsx
  src/components/detail/detailPage.tsx
  src/components/header/header.tsx
  src/components/mainPage/heroSection.tsx
  src/components/mainPage/mainPage.tsx
  src/components/reportPage/calendar.tsx
  src/components/search/resultSearchPage.tsx
Labels: 💄 Design

#48 [Design,Feat]상세페이지 찜하기 기능&토스트알림&회원가입페이지 인증코드 체크 이모지 추가
  package-lock.json
  package.json
  public/icons/bookHeart.svg
  src/apis/book/bookApi.ts
  src/app/layout.tsx
  src/app/signup/page.tsx
  src/components/detail/bookHeart.tsx
  src/components/detail/detailPage.tsx
  src/hooks/detail/useBookHeart.ts
  src/types/index.ts
  tailwind.config.js
Labels: ✨ Feat, 💄 Design
